Boards B-C and M translated (Spanish)
Gadgetoid/Pinout.xyz pull request #348
Opened 2019-10-15 17:52 UTC by IkerGarcia

Boards B-C and M translated to Spanish. Please remove from
src\es\translate all the boards that have already been translated. It
eases the work. I want to translate all of them in the next weeks. Thank
you.

2019-11-14 00:03 UTC, gatuno1 requested changes
Sugiero revisar uso de signos de puntuación faltantes en muchas de las frases.

2020-08-19 15:01 UTC, Gadgetoid commented
Would love to get these merged if possible- they might be a little bit out of sync with some minor tweaks I made to the English site but should be fine.

@IkerGarcia any thoughts on @gatuno1's suggestions? I can understand very little 😆

2020-10-13 18:01 UTC, IkerGarcia commented
It can be merged with the changes

2026-08-19 10:49 UTC, Gadgetoid commented
Rebased and merged, thank you!

2026-08-19 10:49 UTC, closed without merging